FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install -g @angular/cli@17

RUN npm install

RUN npm install laravel-echo pusher-js --save

COPY . .

EXPOSE 4200

CMD ["ng", "serve", "--host", "0.0.0.0", "--poll", "2000"]