# Use an official Node.js runtime as a parent image
FROM node:22-alpine

# Set the working directory in the container
WORKDIR /app

COPY package.json package-lock.json ./

# Install project dependencies
RUN npm install
#RUN npm install @angular/router

# Copy the rest of the application's source code
COPY . .

EXPOSE 4200

# Command to run the Angular development server.
# from outside the Docker container.
CMD ["npm", "start"]